import './globals.css';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import Header from './component/Header';
import AddProduct from './component/AddComponent';
import { store } from '../../store/store';
import { Provider } from 'react-redux';
import { Providers } from './layout/Provider';

const roboto = Roboto({
  weight: ['400', '700', '900'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={roboto.className}>
      <body
        style={{
          position: 'relative',
          height: '100vh',
          backgroundColor: '#e1e1ea',
        }}
      >
        <Providers>
          <Header />
          {children}
          <AddProduct />
        </Providers>
      </body>
    </html>
  );
}
