import './globals.css';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import Header from './component/Header';
import AddProduct from './component/AddComponent';
import { Provider } from 'react-redux';
import { store } from '../../store/store';

const roboto = Roboto({
  weight: ['400', '700', '900'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  productcard,
  productfunctions,
}: {
  children: React.ReactNode;
  productcard: React.ReactNode;
  productfunctions: React.ReactNode;
}) {
  return (
    <html lang="en" className={roboto.className}>
      <Provider store={store}>
        <body
          style={{
            position: 'relative',
            height: '100vh',
            backgroundColor: '#e1e1ea',
          }}
        >
          <Header />
          {children}
          {productcard}
          {productfunctions}
          <AddProduct />
        </body>
      </Provider>
    </html>
  );
}
